namespace:
  name: sandbox

appname: techtrends
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
  dockerRegistry: handuy1992

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 250m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111